# IP for multiplexer to listen on
Listen = ":18833"
# UDP buffer size for sending
Buffer = 256

Route = [
    "127.0.0.1:9999"
]

[Log]
# Log short filenames
Debug = true
# Log in local time
#LocalTime = true
